import { OnChanges, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';
import { RxStompService } from '@stomp/ng2-stompjs';
import { CommonTranslationService } from '../../common-translation/common-translation.service';
import { UtilityService } from '../../services/utility.service';
import { AuthService } from '../../services/Authentication/auth.service';
import { DecodedTokenService } from '../../services/Authentication/decoded-token.service';
import { LogoutUtilityService } from '../../services/logout-utility.service';
import { TopNavBarService } from '../../services/top-nav-bar.service';
import { TopologyService } from '../../services/topology.service';
import { TokenHandlingService } from '../../services/Authentication/token-handling.service';
import * as ɵngcc0 from '@angular/core';
export declare class TopNavBarComponent implements OnInit, OnChanges {
    private _router;
    private _route;
    translate: TranslateService;
    private rxStompService;
    private commonTranslationService;
    private utilityService;
    private authService;
    private decodedTokenService;
    private logoutService;
    private topNavBarService;
    private topologyService;
    private tokenHandlingService;
    lastRefresh: string;
    userFirstName: string;
    userLastName: string;
    topologyData: any;
    companyName: any;
    calendarDate: any;
    hideLanguage: Boolean;
    isConfigApp: Boolean;
    showMenu: Boolean;
    hideAppSwitcher: boolean;
    loginPagesFlag: boolean;
    appName: string;
    showGamingDay: boolean;
    gamingDay: string;
    nextRollTIme: any;
    gamingDaysArr: any;
    breadcrumbList: any;
    selectedGamingDay: any;
    constructor(_router: Router, _route: ActivatedRoute, translate: TranslateService, rxStompService: RxStompService, commonTranslationService: CommonTranslationService, utilityService: UtilityService, authService: AuthService, decodedTokenService: DecodedTokenService, logoutService: LogoutUtilityService, topNavBarService: TopNavBarService, topologyService: TopologyService, tokenHandlingService: TokenHandlingService);
    ngOnInit(): void;
    ngOnChanges(changes: any): void;
    getCurrentCalendarDate(): void;
    setCalendarGamingDay(index: any, gday: any): void;
    getLastRefresh(): void;
    hideLanguageMenu(): void;
    checkIfConfigApp(): void;
    getUserName(): void;
    logout(): void;
    toggleTranslation(): void;
    refresh(): void;
    getTopologyData(): void;
    initTopologyData(): void;
    static ɵfac: ɵngcc0.ɵɵFactoryDef<TopNavBarComponent, never>;
    static ɵcmp: ɵngcc0.ɵɵComponentDefWithMeta<TopNavBarComponent, "app-top-nav-bar", never, { "appName": "appName"; "showGamingDay": "showGamingDay"; "gamingDay": "gamingDay"; "nextRollTIme": "nextRollTIme"; "gamingDaysArr": "gamingDaysArr"; "breadcrumbList": "breadcrumbList"; "selectedGamingDay": "selectedGamingDay"; }, {}, never, never>;
}

//# sourceMappingURL=top-nav-bar.component.d.ts.map